### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by Tiebe** [DaRealBerlm/SaveTheWorldDailyRewards#2]
Hey again,

I'm trying to make some changes to the project, but I can't seem to figure out how to build it. I'm currently using Visual Studio 2019, but all I get is this:

![image](https://user-images.githubusercontent.com/9307389/112850618-78c5c880-90aa-11eb-9a4b-3b9bbfbb7d72.png)

**Comment by Tiebe** [comment]
How do I get one exe file, with the 2 python files, instead of all the dlls?

**Comment by DhrumanGupta** [comment]
So this is the default build. This also does work perfectly, but if you want to build into 1 file, you need to build via the publish tab.
Just right-click on the project name, and click publish. Then open publishing settings, and select the option that says build 1 file (I think it is only available if you chose a specific platform instead of portable).

You will need to drag and drop the python files yourself.

**Comment by Tiebe** [comment]
Alright, thank you! Is there any specific reason that you went for 2 separate Python files, instead of doing everything in C#?

**Comment by DhrumanGupta** [comment]
I originally wanted to do all this in c#. If you look in the stwRewards script, it does a post with empty content to claim the reward.

This did not work in c#. I tried null, an empty dictionary, an encoded form with a null and empty content for the post's body, but it just didnt work.

At this point, I just wanted to get it working because I originally planned to have this for myself

**Comment by Tiebe** [comment]
I think I might have figured it out. I'm testing now.


Edit: Fortnite update. I'll test in a bit


Edit: I have this at the end of the json, also looks good

`"notifications":[{"type":"daily_rewards","primary":true,"daysLoggedIn":44,"items":[{"itemType":"AccountResource:eventcurrency_scaling","itemGuid":"71b0d568-9fa0-4c2c-a895-30c9991a21c6","itemProfile":"campaign","quantity":20},{"itemType":"CardPack:cardpack_bronze","itemGuid":"c4e6c3af-5440-4c23-ae70-7aa2bef6025b","itemProfile":"campaign","attributes":{"pack_source":"Schedule"},"quantity":1}]}],"profileCommandRevision":1115,"serverTime":"2021-03-30T12:02:15.912Z","responseVersion":1}`

Edit: Update finished, starting STW now.

EDIT: IT WORKS!!! Will be submitting PR soon!
